version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/locpin-server"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/locpin-client"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
